# UBCUAS Gitlab-CI configuration

image: docker

services:
  - docker:dind

before_script:
  - apk add --no-cache bash make

variables:
  LC_ALL: 'C.UTF-8'
  LANG: 'C.UTF-8'
  GIT_STRATEGY: fetch
  GIT_SUBMODULE_STRATEGY: recursive

Build Docker x64:
  stage: build
  tags:
    - docker
  script:
    - make docker

Publish Docker x64:
  stage: deploy
  tags:
    - docker
  script:
    - docker login -u "$DOCKER_HUB_USER" -p "$DOCKER_HUB_PASSWORD"
    - make docker-publish
  when: on_success
  only:
    - master

